// Auth Types
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"

// AI Types
export const AI_MAKE_PLAY = "AI_MAKE_PLAY";
export const AI_RE_DRAW = "AI_RE_DRAW";
export const AI_PLAY_SINGLE_TILE = "AI_PLAY_SINGLE_TILE";

// Gameplay Types
export const ADD_BAG_EXCHANGE_CACHE = "ADD_BAG_EXCHANGE_CACHE";
export const PLAYER_DRAW_FROM_BAG = "PLAYER_DRAW_FROM_BAG";
export const PLAYER_CLEAR_CACHE = "PLAYER_CLEAR_CACHE";
export const PLAYER_VALID_PLAY_SUCCESS = "PLAYER_VALID_PLAY_SUCCESS";
export const PLAYER_UPDATE_CURRENT_PLAY = "PLAYER_UPDATE_CURRENT_PLAY";
export const PLAYER_CLEAR_CURRENT_PLAYS = "PLAYER_CLEAR_CURRENT_PLAYS";
export const PLAYER_SKIP_TURN = "PLAYER_SKIP_TURN";
export const INCREMENT_SKIP_TURN_COUNT = "INCREMENT_SKIP_TURN_COUNT"
export const RESET_SKIP_TURN_COUNT = "RESET_SKIP_TURN_COUNT"
export const UPDATE_GAME_RESULT = "UPDATE_GAME_RESULT"

// Game Set up, save, load types
export const INITIAL_GAME_SETUP = "INITIAL_GAME_SETUP";
export const LOAD_SAVED_GAME_SETUP = "LOAD_SAVED_GAME_SETUP";
export const SAVE_UPDATE_GAME_SUCCESS = "SAVE_UPDATE_GAME_SUCCESS"
export const DELETE_GAME_SUCCESS = "DELETE_GAME_SUCCESS"

// Refresh Types
export const AUTH_POST_REFRESH = "AUTH_POST_REFRESH";
export const MAIN_POST_REFRESH = "MAIN_POST_REFRESH";

// Message Types
export const UPDATE_MESSAGES = "UPDATE_MESSAGES";
export const NEW_GAME_MESSAGE = "NEW_GAME_MESSAGE";
export const CLEAR_MESSAGES = "CLEAR_MESSAGES"

// Theme Types
export const UPDATE_THEME_SUCCESS = 'UPDATE_THEME_SUCCESS';

// Word Search Types
export const GET_RELATIVE_WORDS_SUCCESS = "GET_RELATIVE_WORDS_SUCCESS";
export const GET_ALL_WORDS_SUCCESS = "GET_ALL_WORDS_SUCCESS";
export const CLEAR_SEARCH_SUCCESS = "CLEAR_SEARCH_SUCCESS";

// Settings Types
export const GET_SETTINGS_SUCCESS = "GET_SETTINGS_SUCCESS";
export const UPDATE_SETTINGS_SUCCESS = "UPDATE_SETTINGS_SUCCESS";
export const RESET_SETTINGS_SUCCESS = "RESET_SETTINGS_SUCCESS";

// Error Types
export const SERVER_ERROR = "SERVER_ERROR";
export const AUTH_ERROR = "AUTH_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const APP_ERROR_HIDE = "APP_ERROR_HIDE"
export const APP_ERROR_SHOW = "APP_ERROR_SHOW"

